Moved sandbox from my repo
beshu-tech/ror-sandbox pull request #1
Opened 2021-02-22 19:57 UTC by pielas

2021-03-12 20:15 UTC, coutoPL requested changes

2021-03-12 20:15 UTC, coutoPL commented on clean.sh
> +. ./dc-internals/common.sh
what about shebang?

2021-03-12 20:15 UTC, coutoPL commented on clean_all.sh
> +. ./dc-internals/common.sh
here and in other scripts too

2021-03-12 20:15 UTC, coutoPL commented on dc-internals/common.sh
> +  n|no|f|false|0) export KIBANA_OSS_ELASTICSEARCH_ADDRESS=172.17.0.1:9200 ;;
please confirm that this address will be always the same

2021-03-12 20:15 UTC, coutoPL commented on readme.md
> +1. Make sure that you have Docker and Docker Compose installed on your system.
how can I do it?

2021-03-12 20:15 UTC, coutoPL commented on readme.md
> +* `run_kibana.sh` - will build and run the Kibana service. You can use the optional `--eshome` or `-e` parameter to run Kibana OSS dedicated to work with `eshome` ES instance located in `elasticsearc
example here would be great

2021-03-12 20:15 UTC, coutoPL commented on readme.md
> +* `prepare_dc_for_custom_use.sh` - will prepare sandbox to use docker-compose manually. Remember to use it with `source ./prepare_dc_for_custom_use.sh`
why do we need to use `source`?

2021-05-15 12:14 UTC, pielas commented on conf/env_configuration
> +ELASTICSEARCH_VERSION=7.2.1
I used 7.11.2 because I noticed that ROR 1.29.0 supports kibana up to 7.11.2

2021-05-15 12:18 UTC, pielas commented on conf/env_configuration
> +USING_DOCKER_FOR_MAC_OR_WINDOWS=y
no :D I committed it by mistake, because I'm using this setting

2021-05-15 12:22 UTC, pielas commented on clean.sh
> +. ./dc-internals/common.sh
I left these scripts without it because it looked that mac os interpreter doesn't do anything with it. However it would be probably good to include it

2021-05-15 13:13 UTC, pielas commented on dc-internals/common.sh
> +  n|no|f|false|0) export KIBANA_OSS_ELASTICSEARCH_ADDRESS=172.17.0.1:9200 ;;
I couldn't find anything in doc specifying that this address will always be the same. However this page https://docs.docker.com/network/network-tutorial-standalone/ mentions that 172.17.0.1 is default gateway address of bridge network

2021-05-15 15:24 UTC, pielas commented on readme.md
> +* `prepare_dc_for_custom_use.sh` - will prepare sandbox to use docker-compose manually. Remember to use it with `source ./prepare_dc_for_custom_use.sh`
It's because I'm setting some environment variables there to use later by `docker-compose`. Using `source` executes script in current scope, not child scope, thanks to that all exported env variables are still available when script finishes. I'm open If you have better idea on how to handle such case

2021-05-17 15:57 UTC, coutoPL approved these changes

2021-05-17 15:58 UTC, merged